import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Nav } from "./components/navbar/CornerNav";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar overscroll-none scroll-smooth ">
      <body
        className={`${nunito.variable} h-[calc(100dvh)] w-full overflow-x-hidden `}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
